### ISSUE TITLE
Order of includes in style.scss causing problems

### ISSUE THREAD

**Issue by andyjessop** [slightlyoffbeat/brew#15]
The "custom-variables" import is done after a lot of the imports that use some of the custom variables so they don't get applied when compiling. In my version I moved the @import("custom-variables") to just below the reset imports and it works fine now.

**Comment by slightlyoffbeat** [comment]
i've updated the LESS files, but I haven't been able to keep the SASS files up to date. SASS support is being removed for now until I can figure out how to keep both up to date.
