### ISSUE TITLE
Error when compiling to Less

### ISSUE THREAD

**Issue by mariacecil** [slightlyoffbeat/brew#18]
When I compile the Less using WinLess I encounter different Error on WinLess.
Like Variable Undefined on the wp-styles.less, Box-shadow undefined in content.less, etc.

**Comment by slightlyoffbeat** [comment]
oops.  wp-styles.less should have been deleted.  Remove it and try compiling style.less again.  Let me know if that fixes it.

**Comment by nicholasalanbrown** [comment]
I tried to compile on Mac using LESS.app after simply changing the location of the .homebanner image and it threw tons of errors, and I see no changes reflected in the browser styles. What am I doing wrong?

**Comment by slightlyoffbeat** [comment]
Can you list what some of the errors were?  There's a chance you might have just removed a bracket or something?
