### ISSUE TITLE
Home page title

### ISSUE THREAD

**Issue by purgeru** [slightlyoffbeat/brew#24]
Every time when I install the theme the static front page does not have the title in the browser's tab. There is always a link showing. 
On the other pages like Contact page, it displays the title.

**Comment by slightlyoffbeat** [comment]
You are right.  I recently noticed this as well.  I'll mark it to be fixed soon.

**Comment by slightlyoffbeat** [comment]
Fixed!  It is live in Dev, but it will be merged to master soon.
