### ISSUE TITLE
Postname not working in WP 3.8.1

### ISSUE THREAD

**Issue by quatroweb** [slightlyoffbeat/brew#25]
When changing the "Links Permanents" to /%postname%/ all pages displays Page not found.

Actually, the homepage is showing fine, but all other pages are not showing for some reason.

When changing back to Default (http://localhost/theme/?p=123) then the theme works fine.

I use Wordpress 3.8.1 (I was wondering if the theme works with that version?)

**Comment by slightlyoffbeat** [comment]
hmm, i just tested on the latest version of wordpress and I didn't have any issues.  Are you using any caching plugins?  Do any of the other options work?

**Comment by quatroweb** [comment]
I made an installation of Wordpress 3.8.1 with no plugins on my localhost wamp and it gave the "Page not found"

Well though, in the meantime I also made the same installation on my public server and the theme worked fine with /%postname%/

Conclusion, it have to be something with my localhost.
