### ISSUE TITLE
LESS causing compile errors

### ISSUE THREAD

**Issue by AlfalfaAnne** [slightlyoffbeat/brew#27]
Just downloaded the latest version and it's giving syntax errors when I try to compile LESS. I replaced the folder with an earlier version that I had downloaded and it compiles ok. The issues seem to be the missing variables.less file and some syntax errors in mixins.

**Comment by slightlyoffbeat** [comment]
Just fixed this. I accidentally left bootstrap.less in when I updated to 3.1.  Delete that from less/bootstrap and you should be good to go.

**Comment by AlfalfaAnne** [comment]
Great - thanks!
