### ISSUE TITLE
single post navigation

### ISSUE THREAD

**Issue by purgeru** [slightlyoffbeat/brew#28]
How about if single post pagination would be in single.php file instead in coments.php. 
When I implemented the Facebook Comment system the navigation looks beter if it's in single post file and still under the author profile.
![brew](https://f.cloud.github.com/assets/3590917/2314427/c7337122-a316-11e3-8756-23847ac27766.jpg)

**Comment by slightlyoffbeat** [comment]
You are right.  It should be on single.php.  I'll add this to the to-do list.

**Comment by slightlyoffbeat** [comment]
this has been changed and will be in the next update.
