### ISSUE TITLE
Glyphicons slow loadtime in submenu

### ISSUE THREAD

**Issue by quatroweb** [slightlyoffbeat/brew#29]
I am using the glyphicons in the menu. Actually in the submenus.

I was aware that clicking in the menu to see the items in the dropdown, the glyphicons are appearing just 2-3 seconds after (The texts of the items is appearing normally).

My question is if it has something to do with the theme?
Does this issue appear to other users of the theme?

**Comment by danielktaylor** [comment]
For others having this problem - the browser is lazily loading the glyphicons. Stick one somewhere else in your main page and it will load them prior to the menu being clicked.
