### ISSUE TITLE
Redux framework

### ISSUE THREAD

**Issue by purgeru** [slightlyoffbeat/brew#31]
I dont know where to ask, I dont really know how to use redux framework, are there any good tips. I want to use color picker for background and link. Do I use the framework options?

**Comment by slightlyoffbeat** [comment]
Hello Purgeru,

Take a look around the redux website.  Color picker is an option:

https://github.com/ReduxFramework/redux-framework/wiki/Fields#wiki-color

You can see an example of the redux framework in use here:

https://github.com/slightlyoffbeat/brew/blob/master/library/option-config.php

**Comment by purgeru** [comment]
Whatever function I add it is not working, only those default options. The Custom CSS editor and the color picker are not working.
