### ISSUE TITLE
Cannot  style the admin login page.

### ISSUE THREAD

**Issue by purgeru** [slightlyoffbeat/brew#36]
I can not add the logoI changed in login.css even the link to my site does not workin, it redirects to the wordpres site.

**Comment by slightlyoffbeat** [comment]
If it redirects, it doesn't sound like a BREW issue.  I don't really recommend theming the admin panel, but if you just want to theme the login page, add the following code (it is currently in /library/admin.php).  Just take the code needed for themeing the login.  I would add it to your function.php and then make updates to login.css:

ADD TO functions.php:

/************\* CUSTOM LOGIN PAGE *****************/

// calling your own login css so you can style it

//Updated to proper 'enqueue' method
//http://codex.wordpress.org/Plugin_API/Action_Reference/login_enqueue_scripts
function bones_login_css() {
    wp_enqueue_style( 'bones_login_css', get_template_directory_uri() . '/library/css/login.css', false );
}

// changing the logo link from wordpress.org to your site
function bones_login_url() {  return home_url(); }

// changing the alt text on the logo to show your site name
function bones_login_title() { return get_option( 'blogname' ); }

// calling it only on the login page
add_action( 'login_enqueue_scripts', 'bones_login_css', 10 );
add_filter( 'login_headerurl', 'bones_login_url' );
add_filter( 'login_headertitle', 'bones_login_title' );
