### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by Tanmccuin** [slightlyoffbeat/brew#40]
@slightlyoffbeat - was psyched to see a bootstrap variation of Bones, I've been building off of Bones for a few years now but have been wanting to incorporate bootstrap though i'm not quite sure if i'm ready to throw my dev workflow completely out the window and be forced to adopt Root's theme wrapper concept. 
However I'm not seeing alot of movement here the past few months, and noticed that bootstrap wasn't up to date. Has development dried up or are things just slow at the moment? Thanks!

**Comment by FrancescoBorzi** [comment]
Good question, I'm interested in contributing. I made some improvements which are still waiting to be merged: https://github.com/slightlyoffbeat/brew/pull/39

**Comment by slightlyoffbeat** [comment]
Hello,

I apologize for the lack of development and maintenance.  I plan to continue.  A few months back my wife and I learned we are having a kid, so my honey-do list is taking over my evenings :package: 

 I will schedule some time to tackle these pull requests and make progress towards 1.0.

**Comment by paulgc34** [comment]
cmb_Meta_Box upload image shows error when removing all previously uploaded images.

When creating a meta box with file uploads for images this error is displayed after removing all previously uploaded images.

Invalid argument supplied for foreach() in /cmb_Meta_Box_types.php on line 443

The error only show's up if you have uploaded all some images then remove them all. If you remove only some of the images no error is displayed. It's only when you have removed all previously uploaded images.

I have found this which addresses the issue but can't seem to figure out how to update the fix with brew: WebDevStudios/Custom-Metaboxes-and-Fields-for-WordPress#464

Paul

**Comment by slightlyoffbeat** [comment]
added a new dev branch with a few updates.  Should also address meta box issue (updated to version 1.2).  Will merge to master soon.
